version: '3'
services:
    # proxy:
    #     container_name: immow24-nginx
    #     image: nginx:1.21
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.nginx
    #     ports:
    #         - '94:80'
    #     restart: always

    database:
        container_name: immow24-database
        image: postgis/postgis:13-master
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - 5104:5432

    cache:
        container_name: immow24-cache
        image: redis:7

    directus:
        ports:
            - 8060:8055
        container_name: immow24-directus
        build:
            context: .
            dockerfile: Dockerfile
        image: directus/directus:10.12.1
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            KEY: '5db28615-6599-1a5e-9a3a-c41920b2530e'
            SECRET: '67b18164-bb55-c225-ad1c-c263c402285e'

            # Activate websockets
            WEBSOCKETS_ENABLED: 'false'

            # Get vrom environment variable
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}

            # Other Settinsg
            EMAIL_FROM: ${EMAIL_FROM}

            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

            CACHE_ENABLED: true
            # Clear Cache if data is altered or added
            CACHE_AUTO_PURGE: true
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'

            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            PUBLIC_URL: ${PUBLIC_URL}
            CORS_ENABLED: true

        command: >
            sh -c "
            chown -R node:node /directus/extensions /directus/uploads &&
            exec directus start
            "

        # Environment variables can also be defined in a file (for example `.env`):
        # env_file:
        #     - .env
